application: datatools01
version: 1-0-1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: assets/images/favicon.ico
  upload: assets/images/favicon.ico

- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt

- url: /js
  static_dir: assets/js

- url: /css
  static_dir: assets/css


- url: /images
  static_dir: assets/images


# env info
- url: /env
  script: env.php

# env info
- url: /test
  script: test.php

# api root
- url: /v1/.*
  script: v1/index.php



