application: datatools01
version: 1-0-1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# env info
- url: /env
  script: env.php

# api root
- url: /v1/.*
  script: v1/index.php
